### ISSUE TITLE
Installation information in README

### ISSUE THREAD

**Issue by jackhannah95** [johncassil/stringr.plus#2]
Hi,

Thanks for your great package! It has spared me a lot of googling about regex.

I had a little trouble installing the package at first, because I was using a slightly older version of devtools which expected the default branch to be called 'master' rather than 'main':

```r
devtools::install_github("johncassil/stringr.plus")
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  No commit found for the ref master

  Did you spell the repo owner (`johncassil`) and repo name (`stringr.plus`) correctly?
  - If spelling is correct, check that you have the required permissions to access the repo.
```

It's not a problem in the latest release of devtools, but for someone unknowingly using an older version, it's a very minor headache.

Would it be possible to update the installation information in the README to

``` r
devtools::install_github("johncassil/stringr.plus", ref = "main")
```
to prevent anyone else with a similarly old version from having the same issue?

Thanks!

**Comment by johncassil** [comment]
Wow!  Thanks for bringing this up.

I had no idea this was a thing. I was actually considering remotes::install_github() instead... I just skimmed through https://github.com/r-lib/remotes/issues/508 and I'm seeing that they seemed to have created a workaround that is working on CRAN.  I will update the README.

Thanks again!
