### ISSUE TITLE
New function idea: str_context

### ISSUE THREAD

**Issue by abidawson** [johncassil/stringr.plus#4]
Hi there,

A while back I wrote a function to return a window of a given size around a pattern. This is helpful for understanding the context of a detected string (e.g. how is this string used in my data, especially for very long blocks of text) as well as detecting false positives. 

For example:
`str_context(string = "In a hole in the ground there lived a hobbit.", pattern = "ground", window_size = 6)`
would return `"...n the ground there..."`

There would also be a parameter for how many matches to return.

Does this sound like an interesting/useful function for your package? If so I'd be happy to submit as a Hacktoberfest PR. Thanks!

**Comment by johncassil** [comment]
Hi Abi!

That actually sounds really useful and I think it would be great to include. 

What do you think about making the name a little more verb-y like str_extract_context() ?

Thanks!

**Comment by johncassil** [comment]
Just wanted to say, let me know if you need any help!

**Comment by abidawson** [comment]
Thanks, glad it sounds useful. Making the name more verb-y makes sense, and I'll be able to get something over to you in the next few days I think. Will let you know if I have other questions!
